import type { WorkbenchState } from "./types";

export const initialState: WorkbenchState = {
  notes: [
    {
      id: "note_seed_1",
      text: "上周与王总、李律师沟通，王总提到华东新能源集团近期可能有新能源装备企业并购和供应链争议需求。李律师与集团法务陈法务比较熟，可以协助约见。王总最早由张总介绍认识，关系温度还可以。",
      source: "样例记事",
      sensitivity: "团队内部",
      status: "已入库",
      createdAt: "2026-06-25T10:30:00.000Z",
    },
    {
      id: "note_seed_2",
      text: "星河资本最近关注半导体并购基金，周总希望了解团队在基金设立、投后争议和被投企业合规上的经验。下次可准备一页案例简报。",
      source: "样例记事",
      sensitivity: "团队内部",
      status: "已入库",
      createdAt: "2026-06-28T15:10:00.000Z",
    },
  ],
  people: [
    {
      id: "person_sheng",
      name: "盛老师",
      role: "锦天城律师团队负责人",
      organizationId: "org_jtc",
      organizationName: "锦天城律师事务所",
      tags: ["团队负责人", "关系中枢"],
      resources: ["团队专业能力", "客户关系维护"],
      needs: [],
      introPath: "系统中心人物",
      relationshipTemperature: 5,
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-07-01",
      sourceNoteIds: [],
      notes: "工作台围绕盛老师的人脉记忆、法律服务机会和合伙人资源联想构建。",
    },
    {
      id: "person_wang",
      name: "王总",
      role: "企业高管/客户联系人",
      organizationId: "org_energy",
      organizationName: "华东新能源集团",
      tags: ["客户资源", "新能源", "并购线索"],
      resources: ["集团业务入口", "产业项目信息"],
      needs: ["并购重组", "争议解决", "合规监管"],
      introPath: "张总介绍认识",
      relationshipTemperature: 4,
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-25",
      sourceNoteIds: ["note_seed_1"],
      notes: "可围绕新能源装备并购、供应链争议和并购合规切入。",
    },
    {
      id: "person_li",
      name: "李律师",
      role: "律师/合作方",
      tags: ["专业合作方", "可引荐"],
      resources: ["认识华东新能源集团法务陈法务"],
      needs: [],
      introPath: "合伙人资源",
      relationshipTemperature: 4,
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-25",
      sourceNoteIds: ["note_seed_1"],
      notes: "可能协助约见华东新能源集团法务。",
    },
    {
      id: "person_zhang",
      name: "张总",
      role: "外部资源方",
      tags: ["介绍人", "资源连接"],
      resources: ["介绍王总"],
      needs: [],
      introPath: "早期关系入口",
      relationshipTemperature: 3,
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-25",
      sourceNoteIds: ["note_seed_1"],
      notes: "王总的介绍来源。",
    },
    {
      id: "person_chen",
      name: "陈法务",
      role: "集团法务负责人",
      organizationId: "org_energy",
      organizationName: "华东新能源集团",
      tags: ["法律需求入口", "关键联系人"],
      resources: ["集团法务需求入口"],
      needs: ["合规监管", "争议解决"],
      introPath: "李律师认识，待确认可约路径",
      relationshipTemperature: 2,
      confidence: "待核实",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_1"],
      notes: "目前仅为间接关系，接触前需确认介绍路径。",
    },
    {
      id: "person_zhou",
      name: "周总",
      role: "投资机构负责人",
      organizationId: "org_capital",
      organizationName: "星河资本",
      tags: ["资本资源", "基金需求"],
      resources: ["半导体并购基金资源"],
      needs: ["基金/资管", "投融资", "合规监管"],
      introPath: "待补充",
      relationshipTemperature: 3,
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-28",
      sourceNoteIds: ["note_seed_2"],
      notes: "关注基金设立、投后争议和被投企业合规经验。",
    },
  ],
  organizations: [
    {
      id: "org_jtc",
      name: "锦天城律师事务所",
      industry: "法律服务",
      tags: ["律所", "团队平台"],
      keyPeopleIds: ["person_sheng"],
      legalNeeds: [],
      relationshipStatus: "内部主体",
      confidence: "已确认",
      sensitivity: "团队内部",
      sourceNoteIds: [],
      notes: "工作台用于锦天城律师团队内部的人脉与法律服务机会管理。",
    },
    {
      id: "org_energy",
      name: "华东新能源集团",
      industry: "新能源",
      tags: ["潜在客户", "新能源", "集团客户"],
      keyPeopleIds: ["person_wang", "person_chen"],
      legalNeeds: ["并购重组", "争议解决", "合规监管"],
      relationshipStatus: "接触中",
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-25",
      sourceNoteIds: ["note_seed_1"],
      notes: "存在新能源装备并购、供应链争议等潜在线索。",
    },
    {
      id: "org_capital",
      name: "星河资本",
      industry: "投资机构",
      tags: ["资本资源", "基金"],
      keyPeopleIds: ["person_zhou"],
      legalNeeds: ["基金/资管", "投融资", "争议解决"],
      relationshipStatus: "接触中",
      confidence: "已确认",
      sensitivity: "团队内部",
      lastInteractionAt: "2026-06-28",
      sourceNoteIds: ["note_seed_2"],
      notes: "关注半导体并购基金及投后法律服务。",
    },
  ],
  relationships: [
    {
      id: "rel_1",
      fromKind: "person",
      fromId: "person_zhang",
      toKind: "person",
      toId: "person_wang",
      label: "介绍认识",
      strength: 4,
      confidence: "已确认",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_1"],
    },
    {
      id: "rel_2",
      fromKind: "person",
      fromId: "person_li",
      toKind: "person",
      toId: "person_chen",
      label: "认识/可协助约见",
      strength: 3,
      confidence: "待核实",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_1"],
    },
    {
      id: "rel_3",
      fromKind: "person",
      fromId: "person_wang",
      toKind: "organization",
      toId: "org_energy",
      label: "集团联系人",
      strength: 4,
      confidence: "已确认",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_1"],
    },
  ],
  interactions: [
    {
      id: "inter_1",
      date: "2026-06-25",
      title: "华东新能源集团线索沟通",
      summary:
        "王总提到新能源装备企业并购和供应链争议需求；李律师可能协助约见集团法务陈法务。",
      participantIds: ["person_wang", "person_li"],
      organizationIds: ["org_energy"],
      opportunityIds: ["opp_1"],
      sensitivity: "团队内部",
      sourceNoteId: "note_seed_1",
    },
    {
      id: "inter_2",
      date: "2026-06-28",
      title: "星河资本基金需求沟通",
      summary: "周总关注半导体并购基金、基金设立、投后争议和被投企业合规经验。",
      participantIds: ["person_zhou"],
      organizationIds: ["org_capital"],
      opportunityIds: ["opp_2"],
      sensitivity: "团队内部",
      sourceNoteId: "note_seed_2",
    },
  ],
  opportunities: [
    {
      id: "opp_1",
      title: "华东新能源集团 - 新能源并购与争议解决",
      stage: "线索",
      organizationId: "org_energy",
      peopleIds: ["person_wang", "person_chen"],
      practiceAreas: ["并购重组", "争议解决", "合规监管"],
      nextStep: "通过李律师确认能否约见陈法务，并准备会前简报。",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_1"],
    },
    {
      id: "opp_2",
      title: "星河资本 - 半导体并购基金法律服务",
      stage: "接触中",
      organizationId: "org_capital",
      peopleIds: ["person_zhou"],
      practiceAreas: ["基金/资管", "投融资", "争议解决"],
      nextStep: "准备一页基金设立与投后争议案例简报。",
      sensitivity: "团队内部",
      sourceNoteIds: ["note_seed_2"],
    },
  ],
  tasks: [
    {
      id: "task_1",
      title: "确认李律师能否协助约见陈法务",
      dueText: "本周",
      status: "待办",
      linkedPersonIds: ["person_li", "person_chen"],
      linkedOrganizationIds: ["org_energy"],
      linkedOpportunityIds: ["opp_1"],
      sourceNoteIds: ["note_seed_1"],
    },
    {
      id: "task_2",
      title: "为星河资本准备基金设立与投后争议案例简报",
      dueText: "下次沟通前",
      status: "待办",
      linkedPersonIds: ["person_zhou"],
      linkedOrganizationIds: ["org_capital"],
      linkedOpportunityIds: ["opp_2"],
      sourceNoteIds: ["note_seed_2"],
    },
  ],
  settings: {
    provider: "mock",
    localEndpoint: "http://intranet-deepseek.local/v1/chat/completions",
    localModel: "deepseek-local",
    retrievalMode: "hybrid",
    theme: "light",
    speechMode: "browser",
    speechLanguage: "zh-CN",
  },
};
